//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bundle_lot
    {
        public bundle_lot()
        {
            this.purchases = new HashSet<purchase>();
            this.sales = new HashSet<sale>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string bundle_name { get; set; }
        public string des { get; set; }
    
        public virtual ICollection<purchase> purchases { get; set; }
        public virtual ICollection<sale> sales { get; set; }
    }
}
