//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class damaged_products
    {
        public int id { get; set; }
        public System.DateTime issue_date { get; set; }
        public int product_id { get; set; }
        public int quantity { get; set; }
        public int warehouse_id { get; set; }
        public string damage_details { get; set; }
    
        public virtual product product { get; set; }
        public virtual warehouse warehouse { get; set; }
    }
}
