//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventoryDBContext : DbContext
    {
        public InventoryDBContext()
            : base("name=InventoryDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bundle_lot> bundle_lot { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<damaged_products> damaged_products { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<purchase> purchases { get; set; }
        public DbSet<sale> sales { get; set; }
        public DbSet<supplier> suppliers { get; set; }
        public DbSet<tax> taxes { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<warehouse> warehouses { get; set; }
    }
}
