//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace InventoryFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.damaged_products = new HashSet<damaged_products>();
            this.purchases = new HashSet<purchase>();
            this.sales = new HashSet<sale>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "Please provide code", AllowEmptyStrings = false)]
        public string code { get; set; }
        [Required(ErrorMessage = "Please provide name", AllowEmptyStrings = false)]
        public string name { get; set; }
        [Required(ErrorMessage = "Please provide unit", AllowEmptyStrings = false)]
        public string unit { get; set; }
        [Required(ErrorMessage = "Please provide size", AllowEmptyStrings = false)]
        public string size { get; set; }
        [Required(ErrorMessage = "Please provide cost", AllowEmptyStrings = false)]
        public double cost { get; set; }
        [Required(ErrorMessage = "Please provide price", AllowEmptyStrings = false)]
        public double price { get; set; }
        [Required(ErrorMessage = "Please provide alert_quantity", AllowEmptyStrings = false)]
        public int alert_quantity { get; set; }
        [Required(ErrorMessage = "Please provide category id", AllowEmptyStrings = false)]
        public int category_id { get; set; }
        [Required(ErrorMessage = "Please provide tax id", AllowEmptyStrings = false)]
        public int tax_id { get; set; }
        
        public string details { get; set; }
        public Nullable<int> stock_quantity { get; set; }
    
        public virtual category category { get; set; }
        public virtual ICollection<damaged_products> damaged_products { get; set; }
        public virtual tax tax { get; set; }
        public virtual ICollection<purchase> purchases { get; set; }
        public virtual ICollection<sale> sales { get; set; }
    }
}
