//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public supplier()
        {
            this.purchases = new HashSet<purchase>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string company { get; set; }
        public string adress { get; set; }
        public string city { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string postal_code { get; set; }
        public string details { get; set; }
    
        public virtual ICollection<purchase> purchases { get; set; }
    }
}
