//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tax
    {
        public tax()
        {
            this.products = new HashSet<product>();
            this.sales = new HashSet<sale>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public double rate { get; set; }
        public string type { get; set; }
        public string tax_id { get; set; }
    
        public virtual ICollection<product> products { get; set; }
        public virtual ICollection<sale> sales { get; set; }
    }
}
