//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace InventoryFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Please provide username", AllowEmptyStrings = false)]
        public string username { get; set; }
        [Required(ErrorMessage = "Please provide Password", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        [StringLength(50, MinimumLength = 8, ErrorMessage = "Password must be 8 char long.")]
        public string password { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }
          [Required(ErrorMessage = "Please provide firstname", AllowEmptyStrings = false)]
        public string firstname { get; set; }
          [Required(ErrorMessage = "Please provide lastname", AllowEmptyStrings = false)]
        public string lastname { get; set; }
          [Required(ErrorMessage = "Please provide phone", AllowEmptyStrings = false)]
        public string phone { get; set; }
          [Required(ErrorMessage = "Please provide user_type", AllowEmptyStrings = false)]
        public int user_type { get; set; }
          [Required(ErrorMessage = "Please provide active", AllowEmptyStrings = false)]
        public int active { get; set; }
        public System.DateTime issue_date { get; set; }
        [Compare("password", ErrorMessage = "Confirm password dose not match.")]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string Conformation_password { get; set; }
          [Required(ErrorMessage = "Please provide user id", AllowEmptyStrings = false)]
        public string user_id { get; set; }
    }
}
