//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse
    {
        public warehouse()
        {
            this.damaged_products = new HashSet<damaged_products>();
            this.purchases = new HashSet<purchase>();
            this.sales = new HashSet<sale>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
    
        public virtual ICollection<damaged_products> damaged_products { get; set; }
        public virtual ICollection<purchase> purchases { get; set; }
        public virtual ICollection<sale> sales { get; set; }
    }
}
